name = "df"
num_frames = 16  # T
max_duration = 40  # D
model_type = "batfd"
dataset = "fakeavceleb"

[optimizer]
#learning_rate = 2e-5
frame_loss_weight = 2.0
modal_bm_loss_weight = 1.0
contrastive_loss_weight = 0.1
contrastive_loss_margin = 0.99
#weight_decay = 0.0001

